### ISSUE TITLE
在哪里判断后端接口返回的状态码，message和data？

### ISSUE THREAD

**Issue by CrazyCat6** [jsxiaosi/vue-xs-admin#10]
这里是不是都是http请求的状态码？
![3](https://github.com/jsxiaosi/vue-xs-admin/assets/38643408/6688b5a6-6477-4e45-b4d1-f45e93738d40)

**Comment by jsxiaosi** [comment]
> 这里是不是都是http请求的状态码？ ![3](https://user-images.githubusercontent.com/38643408/285108361-6688b5a6-6477-4e45-b4d1-f45e93738d40.png)

请求状态码是在`src/utils/axios/index.ts` responseInterceptorsCatch 响应错误拦截器处理的

**Comment by CrazyCat6** [comment]
已解决，感谢
