### ISSUE TITLE
是否有打算添加更多的主题样式

### ISSUE THREAD

**Issue by ghost** [jsxiaosi/vue-xs-admin#2]
是否有打算添加更多的主题样式，自定义配置界面配色等

**Comment by jsxiaosi** [comment]
开始设计的时候想着自定义配色在日常开发使用场景比较少，所以一开始没有想着去做。后面会有计划去做这件事情，目前设置界面过于简单，后续会把设置界面功能变的更加丰富。目前有其他计划正在稳妥的进行中。

后续会有：
1. 更多的设置功能
2. 简易模版（除了系统功能保留，其他页面全部删除）

预计在今年内完成~！

如果想要设置颜色，可以通过scss变量去设置，现在的主题是和element统一配置的，如果想要配置系统设置可以在public/serverConfig.json修改

**Comment by jsxiaosi** [comment]
主题切换的功能，已经添加
