### ISSUE TITLE
页面切换体验不好

### ISSUE THREAD

**Issue by ghost** [jsxiaosi/vue-xs-admin#5]
![image](https://user-images.githubusercontent.com/93296511/199633934-fc88c310-3823-45a5-8cd0-962914c28118.png)

**Comment by jsxiaosi** [comment]
最新代码已经修复，拉取即可

**Comment by ghost** [comment]
拉取最新代码，还是有滑动条，谷歌浏览器

**Comment by jsxiaosi** [comment]
我这里没有复现此问题哦~！线上地址也没有出现此问题了，可以提供一下demo吗？

**Comment by ghost** [comment]
就是线上demo发现问题，拉取最新代码还有同样的问题，【页面切换过程中 仅有短短零点几秒会出现滑动条】

**Comment by jsxiaosi** [comment]
参试一下修改样式.app-main里面的overflow: auto;为：overflow-y: auto;overflow-x: hidden;
