### ISSUE TITLE
theme: 黑色主题的配色优化

### ISSUE THREAD

**Issue by hhstore** [jsxiaosi/vue-xs-admin#6]
# 如题:

- 白色主题, 配色挺好. 
- 黑色主题, 色彩搭配, 个人感觉还可以优化. 
- https://www.happyhues.co/
- 这有个配色方案选择网站, 给出很多套配色, 每套都非常详细, 按钮,页面,背景色,等等.
- 可以参考这个网站, 优化一下配色.

**Comment by jsxiaosi** [comment]
> # 如题:
> * 白色主题, 配色挺好.
> * 黑色主题, 色彩搭配, 个人感觉还可以优化.
> * https://www.happyhues.co/
> * 这有个配色方案选择网站, 给出很多套配色, 每套都非常详细, 按钮,页面,背景色,等等.
> * 可以参考这个网站, 优化一下配色.

因为我是基于element的黑色主题去做的配色，所以没有单独去为黑色主题做设计
