### ISSUE TITLE
怎么配置后台路径前缀？

### ISSUE THREAD

**Issue by CrazyCat6** [jsxiaosi/vue-xs-admin#9]
怎么配置后台路径前缀？
![Uploading 1.png…]()

**Comment by CrazyCat6** [comment]
![1](https://github.com/jsxiaosi/vue-xs-admin/assets/38643408/930cf71e-855e-45a1-974d-39857683e581)

**Comment by jsxiaosi** [comment]
> ![1](https://user-images.githubusercontent.com/38643408/284851450-930cf71e-855e-45a1-974d-39857683e581.png)

<img width="1162" alt="image" src="https://github.com/jsxiaosi/vue-xs-admin/assets/48111694/a19dd6fa-bc2c-45db-825e-a3017e53f186">

**Comment by CrazyCat6** [comment]
固定在这里吗？比如开发、测试、上线不同环境、要手动修改这个吗，能用从.env.development这些配置文件里读取吗？

**Comment by jsxiaosi** [comment]
> 固定在这里吗？比如开发、测试、上线不同环境、要手动修改这个吗，能用从.env.development这些配置文件里读取吗？

你可以在不同环境的env添加baseURL 然后通过 import.meta.env 获取，如果要类型提示在 `types/env.d.ts` 文件中往 `ViteEnv` 添加你定义的环境变量名称即可

**Comment by CrazyCat6** [comment]
好像还是没取到，是我写的有问题吗？
![2](https://github.com/jsxiaosi/vue-xs-admin/assets/38643408/a4e9143b-8f62-465b-8f97-4ddcb490df45)

**Comment by jsxiaosi** [comment]
> 好像还是没取到，是我写的有问题吗？ ![2](https://user-images.githubusercontent.com/38643408/284857123-a4e9143b-8f62-465b-8f97-4ddcb490df45.png)

你定义环境变量名要再前面加上VITE_才能获取到 ，例如：VITE_API_URL，你获取的时候也要import.meta.env.VITE_API_URL
